### ISSUE TITLE
Performance of  PHP vs GO vs NodeJS implementations. 

### ISSUE THREAD

**Issue by wmantly** [librespeed/speedtest#346] opened 2020-08-10 19:38 UTC
## Description
I have set up the PHP, Go and NodeJS librespeed each in there own container(LXC) on the same server. Each container is allowed to use 3 cores (E5-2697 v2 @ 2.70GHz) and 2gb RAM. Each container is proxied via a shared openresty(nginx) performing HTTPS termination and proxying. The 4 containers(3 speedtests and one proxy) are all that is running. The server has a 1gps fiber internet connection and the client has a 1gps fiber internet connection, both hardwired and ping of about 5ms. Using `wget` gets a solid 110-120/mbs in both directions.

From my test, the NodeJS comes closest to the true line speed.

### NodeJS
https://speedtest.gg.vm42.us/
Gets about 900down and 900-1000 up, ping 10ms and jitter ~1ms -- all consistent.

### Go
https://speedtestgo.gg.vm42.us/
Gets about 400-800down and 100-400 up, ping 6-10ms and jitter >1ms

### PHP
https://speedtestphp.gg.vm42.us/
Gets about 400-800down and 100-400 up, ping 6-12ms and jitter .5-2ms

From my tests, the NodeJS version is the best one, but the README says "It's not recommended to use at the moment". Why is this?

**Comment by adolfintel** [comment] 2020-08-10 19:47
That's weird, the Go version should be way faster than the PHP and Node versions. Something on your network might be the cause of this problem. Firewalls and proxies are a prime suspect for this.

The Node version hasn't been updated in a while and will be removed with the next major update, that's why I don't recommend using it.

Contact me at info@fdossena.com if you need help

**Comment by wmantly** [comment] 2020-08-10 19:51
Why did you close this? Its supposed to be a conversation. All the containers are identical in configuration. The use the same network, the same firewall, the same proxy set up in exactly the same manner.

**Comment by bogdanrotariu** [comment] 2020-08-10 19:54
Hey,

Just tested now from 5000km distance. The PHP version was the fastest, please see[1].


[1] https://imgur.com/a/JK0hkvC <https://imgur.com/a/JK0hkvC>



--
Bogdan-Stefan Rotariu
bogdan@rotariu.ro

**Comment by adolfintel** [comment] 2020-08-10 20:08
Sorry, I thought you just wanted help troubleshooting it, I'll leave it open for a while.

In my experience, performance issues like these are caused by network devices doing weird things to the streams. I've seen some switches do it, routers with mesh support, but usually it's firewalls and proxies.
I was never able to replicate these myself to figure out the exact cause, but I suspect it's qos related or maybe has to do with TCP windowing.

**Comment by wmantly** [comment] 2020-08-10 22:25
I see. Besides port 80/HTTP, do any of the implementations require other ports?

**Comment by adolfintel** [comment] 2020-08-11 04:52
No, but for ISP detection it must be allowed to connect to ipinfo.io (HTTPS)

**Comment by wmantly** [comment] 2020-08-14 17:31
After performing a bunch more tests on different networks my initial results were a fluke, and all implementations seem to report the exact same speeds and use about the same memory( with the exception of PHP if you are using apache/php for other things )

**Comment by adolfintel** [comment] 2020-08-14 17:46
Good to know, I'll close the issue then. Feel free to use it again if you have other questions about performance.

**Closed by adolfintel** 2020-08-14 17:46 UTC
