### ISSUE TITLE
Always Unknown ISP on standard ISP

### ISSUE THREAD

**Issue by GerdRuetten** [librespeed/speedtest#603] opened 2024-03-10 21:07 UTC
## Description
I using speedtest as docker compose in the latest version (and testing with dev-branch).
I using the servers.json from your side.
On all ISP i get "Unknown ISP".
Only my own ISP (Deutsche Glasfaser) / Testserver is show me up

## Server
Docker compose with:

```
version: '3.7'
services:
  speedtest:
    container_name: speedtest
    image: ghcr.io/librespeed/speedtest:latest
    restart: always
    environment:
      MODE: dual
      TITLE: "Speedtest - ruetten.ovh"
      TELEMETRY: "true"
      ENABLE_ID_OBFUSCATION: "false"
      REDACT_IP_ADDRESSES: "false"
      PASSWORD: "password"
      EMAIL: "gerd@ruetten.ovh"
      DISABLE_IPINFO: "false"
      DISTANCE: "km"
      WEBPORT: 8686
    ports:
      - "8686:8686" # webport mapping (host:container)
    volumes:
      - ./data/database:/database
      - ./data/servers.json:/servers.json
```
## Client
Chrome

## Steps to reproduce
You can test it under:
[https://speedtest.ruetten.ovh](https://speedtest.ruetten.ovh)

## Expected behaviour
Resolve the ISP

## Screenshots
<img width="810" alt="image" src="https://github.com/librespeed/speedtest/assets/97361636/c32b65ce-2346-40c1-9080-c3059c69f3e0">

My own ISP/Testserver

<img width="828" alt="image" src="https://github.com/librespeed/speedtest/assets/97361636/823d45ba-4153-42cb-afb7-be932b0db41f">

<img width="1703" alt="image" src="https://github.com/librespeed/speedtest/assets/97361636/c865dd75-58ee-4230-a441-9a62e921839a">

**Comment by sstidl** [comment] 2024-03-14 06:02
I think you need to set your own api key for ispinfo
`IPINFO_APIKEY=XXXX
`
in the compose file

**Comment by Razuuu** [comment] 2024-05-03 19:02
My ISP is "Telefónica Germany Gmbh & Co OHG" and i am using librespeed.org. It says Unknown ISP.
https://librespeed.org/results/?id=0cetf22

**Comment by sstidl** [comment] 2024-05-04 07:14
> My ISP is "Telefónica Germany Gmbh & Co OHG" and i am using librespeed.org. It says Unknown ISP. https://librespeed.org/results/?id=0cetf22 IPInfo.io says: org:"AS6805 Telefonica Germany GmbH & Co.OHG",
> 
> ![grafik](https://private-user-images.githubusercontent.com/40471551/327857369-43b6e5bb-33ab-4976-89d5-7540b96856fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MDcwNTgsIm5iZiI6MTcxNDgwNjc1OCwicGF0aCI6Ii80MDQ3MTU1MS8zMjc4NTczNjktNDNiNmU1YmItMzNhYi00OTc2LTg5ZDUtNzU0MGI5Njg1NmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDA3MTIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhMGY2ZDFkMTBhMWEzOTY2ODM0MTY1YzFkM2RjZmQxYTVhOGYyOTgwODYwMWEzOTc1NDNkNWM2MTc3MDQ4YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XQbPO_Nroc3-byfOLHJ0ML4vvdRjSXOfyIxUnjl89fM)

This means that the provider of the service there has to use a new API key.

**Comment by sstidl** [comment] 2024-05-04 07:17
I tested more of the hosts at librespeed.org
@adolfintel  they all showed unknown IP. 
So maybe you have to renew the API key used at your side?

**Comment by adolfintel** [comment] 2024-05-04 11:07
@sstidl The problem is ipinfo itself.

They offered a free unlimited API key a few years ago to this project and all was fine until a few months ago when it started being limited like any other key. I tried contacting their support and had no response. I guess they're no longer offering free keys to open source projects?

**Comment by sstidl** [comment] 2024-05-04 11:25
@adolfintel  
I registered and got my own free plan API key. Maybe you need to register again?

You cannot share the key but use it in your deployment at librespeed.org

**Comment by adolfintel** [comment] 2024-05-04 12:32
@sstidl No, the key they gave us was specifically for this kind of use.

The agreement was that the key was available for free for librespeed.org and individual users of the project, while I would direct businesses to buy a key from them.

It was changed once due to abuse a few years ago, but it was still a free and unlimited key for users of LS.

What bothers me is that they didn't even warn me about this change, it just happened from one day to the next, and they didn't even answer my email. I don't have time to get rid of ipinfo from the project right now, but if anyone wants to do it, I highly encourage to replace it with a local database or something.

**Comment by sstidl** [comment] 2024-05-04 12:49
I just checked the code. You just have to remove the API key from config and it should work.
They have a public API without API key.

**Comment by sstidl** [comment] 2024-05-18 08:58
@adolfintel  i close this issue as it is explained how to fix the situation.

**Closed by sstidl** 2024-05-18 08:58 UTC
